@extends('layouts.app')
@section('title', 'Auditoría')
@section('content')
<x-page-header title="Auditoría" subtitle="Trazabilidad de seguridad y cambios del sistema" />
<div class="mp-card p-3 p-lg-4">
<form class="row g-2 mb-4" method="get"><div class="col-md-3"><input class="form-control" name="action" value="{{ request('action') }}" placeholder="Acción"></div><div class="col-md-3"><select class="form-select" name="user_id"><option value="">Todos los usuarios</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('user_id') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" name="from" type="date" value="{{ request('from') }}" aria-label="Desde"></div><div class="col-md-2"><input class="form-control" name="to" type="date" value="{{ request('to') }}" aria-label="Hasta"></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fecha</th><th>Acción</th><th>Usuario</th><th>Modelo</th><th>IP</th><th>Cambios</th></tr></thead><tbody>@forelse($logs as $log)<tr><td class="text-nowrap">{{ $log->created_at->format('d/m/Y H:i:s') }}</td><td><span class="badge text-bg-secondary">{{ $log->action }}</span></td><td>{{ $log->user?->name ?? 'Sistema' }}</td><td>{{ $log->auditable_type ? class_basename($log->auditable_type).' #'.$log->auditable_id : '—' }}</td><td class="mp-muted">{{ $log->ip_address ?? '—' }}</td><td><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#audit-{{ $log->id }}">Ver</button><div class="modal fade" id="audit-{{ $log->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Evento #{{ $log->id }}</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><h3 class="h6">Valores anteriores</h3><pre class="p-3 rounded bg-body-tertiary">{{ json_encode($log->old_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre><h3 class="h6">Valores nuevos</h3><pre class="p-3 rounded bg-body-tertiary">{{ json_encode($log->new_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></div></div></div></div></td></tr>@empty<tr><td colspan="6" class="mp-empty mp-muted">No hay eventos para estos filtros.</td></tr>@endforelse</tbody></table></div>{{ $logs->links() }}
</div>
@endsection
